"""
User-context Spotify client for the web layer: Authorization Code flow
implemented manually over httpx, used only to save playlists.

Deliberately NOT spotipy's SpotifyOAuth — its file-based token store is
single-user by design (DIAGNOSTIC_REPORT §2) and persists tokens to
disk. Here tokens exist only as TokenSet return values; the caller
(Phase 3) keeps them in the signed session cookie and nowhere else.

Security properties (non-negotiable, build spec T2.2):
- CSRF state comes from secrets.token_urlsafe (generate_state).
- The client secret travels only server-to-server to
  accounts.spotify.com (HTTP Basic on the token endpoint); it never
  appears in the authorize URL handed to the browser, nor in any
  api.spotify.com call.
- Scopes: playlist-modify-private. Nothing else.
- No code path persists or logs a token. The T5.6 diagnostics log the
  granted scope STRING and the /me identity — never token material.
"""
import logging
import os
import secrets
import time
from datetime import date
from typing import Optional
from urllib.parse import urlencode

import httpx
from pydantic import BaseModel

# The playlist-403 diagnostics (T5.6) all live under one logger so a prod
# incident is grep-able in Railway logs by a single name, even though the
# events are emitted from the auth flow.
log = logging.getLogger("venti.web.playlist")

AUTHORIZE_URL = "https://accounts.spotify.com/authorize"
TOKEN_URL = "https://accounts.spotify.com/api/token"
API_BASE = "https://api.spotify.com/v1"

SCOPES = "playlist-modify-private"

PLAYLIST_DESCRIPTION = "A 4-song trajectory. Generated by Venti."

_TIMEOUT = 15.0

# Test seam: tests install an httpx.MockTransport here. None = real network.
_test_transport: Optional[httpx.BaseTransport] = None


class TokenSet(BaseModel):
    access_token: str
    refresh_token: str
    expires_at: int  # unix epoch seconds

    def is_expired(self, skew_seconds: int = 60) -> bool:
        return time.time() >= self.expires_at - skew_seconds


def generate_state() -> str:
    """CSRF state for the authorize redirect. Phase 3 stores it in the
    session cookie; the callback must reject on mismatch."""
    return secrets.token_urlsafe(32)


def build_authorize_url(state: str) -> str:
    """The URL the browser is redirected to. Carries the public client
    id only — never the secret."""
    params = {
        "client_id": _client_id(),
        "response_type": "code",
        "redirect_uri": _redirect_uri(),
        "state": state,
        "scope": SCOPES,
    }
    return f"{AUTHORIZE_URL}?{urlencode(params)}"


def exchange_code(code: str) -> TokenSet:
    resp = _token_request({
        "grant_type": "authorization_code",
        "code": code,
        "redirect_uri": _redirect_uri(),
    })
    payload = resp.json()
    # T5.6: the granted scope is the prime diagnostic for playlist 403s —
    # a token granted without playlist-modify-private authenticates fine
    # (GET /me works) but cannot create a private playlist.
    log.info("token_granted", extra={"scope": payload.get("scope", "")})
    return _to_token_set(payload)


def refresh(refresh_token: str) -> TokenSet:
    resp = _token_request({
        "grant_type": "refresh_token",
        "refresh_token": refresh_token,
    })
    # Spotify may omit refresh_token on refresh; the old one stays valid.
    return _to_token_set(resp.json(), fallback_refresh_token=refresh_token)


def fetch_identity(token: TokenSet) -> dict:
    """GET /v1/me — the account this token acts as. Returns the raw /me
    JSON (id, display_name, ...). Used at connect time for the T5.6
    spotify_identity log line; playlist creation itself needs no user id
    (POST /me/playlists) and never calls this."""
    with _http() as client:
        me = client.get(
            f"{API_BASE}/me",
            headers={"Authorization": f"Bearer {token.access_token}"},
        )
        me.raise_for_status()
        return me.json()


def create_playlist(
    token: TokenSet,
    name: str,
    track_uris: list[str],
    description: str,
) -> str:
    """Create a PRIVATE playlist with the given tracks on the user's
    account; returns its open.spotify.com URL."""
    headers = {"Authorization": f"Bearer {token.access_token}"}
    with _http() as client:
        # POST /me/playlists per Spotify's Feb 2026 Web API migration: the
        # old POST /users/{user_id}/playlists returns a bare 403 for
        # Development Mode apps since 2026-03-09, regardless of token,
        # scope, or allowlist. /me/playlists needs no user_id at all.
        created = client.post(
            f"{API_BASE}/me/playlists",
            headers=headers,
            # "public": False is a permanent product rule AND all that
            # playlist-modify-private permits — Spotify defaults to public,
            # which 403s under our scope. Never rely on the default.
            json={"name": name, "public": False, "description": description},
        )
        created.raise_for_status()
        playlist = created.json()

        added = client.post(
            f"{API_BASE}/playlists/{playlist['id']}/tracks",
            headers=headers,
            json={"uris": track_uris},
        )
        added.raise_for_status()

    return playlist["external_urls"]["spotify"]


def playlist_name(strategy_label: str, on: Optional[date] = None) -> str:
    """Naming convention from the build spec: "Venti — {strategy label} — {Mon D}"."""
    d = on or date.today()
    return f"Venti — {strategy_label} — {d:%b} {d.day}"


def _token_request(data: dict) -> httpx.Response:
    # HTTP Basic to accounts.spotify.com — the only place the client
    # secret is ever sent.
    with _http() as client:
        resp = client.post(
            TOKEN_URL,
            data=data,
            auth=(_client_id(), _client_secret()),
        )
    resp.raise_for_status()
    return resp


def _to_token_set(
    payload: dict,
    fallback_refresh_token: Optional[str] = None,
) -> TokenSet:
    return TokenSet(
        access_token=payload["access_token"],
        refresh_token=payload.get("refresh_token") or fallback_refresh_token,
        expires_at=int(time.time()) + int(payload["expires_in"]),
    )


def _http() -> httpx.Client:
    return httpx.Client(timeout=_TIMEOUT, transport=_test_transport)


def _client_id() -> str:
    return os.environ["SPOTIFY_CLIENT_ID"]


def _client_secret() -> str:
    return os.environ["SPOTIFY_CLIENT_SECRET"]


def _redirect_uri() -> str:
    return os.environ["SPOTIFY_REDIRECT_URI"]
