"""
Spotify integration: search for tracks matching natural-language queries,
queue them, and control playback.

Uses the spotipy library. Requires Premium for playback control.

NOTE: As of November 2024, Spotify deprecated the /v1/recommendations endpoint
and audio-features endpoints for new applications. We use /v1/search instead,
with queries generated by an LLM (see query_generator.py) that translate
emotional waypoints into search terms.
"""
import os
from typing import Optional

import spotipy
from spotipy.oauth2 import SpotifyOAuth


SCOPES = [
    "user-read-playback-state",
    "user-modify-playback-state",
]


class SpotifyClient:
    def __init__(
        self,
        client_id: Optional[str] = None,
        client_secret: Optional[str] = None,
        redirect_uri: str = os.environ.get("SPOTIFY_REDIRECT_URI", "http://127.0.0.1:8888/callback"),
    ):
        auth = SpotifyOAuth(
            client_id=client_id or os.environ["SPOTIFY_CLIENT_ID"],
            client_secret=client_secret or os.environ["SPOTIFY_CLIENT_SECRET"],
            redirect_uri=redirect_uri,
            scope=" ".join(SCOPES),
            cache_path=".spotify_cache",
        )
        self.sp = spotipy.Spotify(auth_manager=auth)

    def find_track_for_query(
        self,
        query: str,
        exclude_track_ids: Optional[set] = None,
    ) -> Optional[dict]:
        """
        Search Spotify for a track matching the natural-language query.
        Returns the most popular track from the top results that hasn't
        been used yet.

        Calls the underlying _get() method directly to bypass a quirk in
        spotipy's search() wrapper that incorrectly sends market=None.
        """
        exclude_track_ids = exclude_track_ids or set()

        results = self.sp._get("search", q=query, type="track", limit=5)

        candidates = [
            t for t in results.get("tracks", {}).get("items", [])
            if t and t["id"] not in exclude_track_ids
        ]
        if not candidates:
            return None

        candidates.sort(key=lambda t: t.get("popularity", 0), reverse=True)
        return candidates[0]

    def build_playlist_from_queries(
        self,
        queries: list[str],
    ) -> list[dict]:
        """Returns list of track dicts, one per query (or fewer if a search fails)."""
        used_ids: set[str] = set()
        tracks = []
        for query in queries:
            track = self.find_track_for_query(query, exclude_track_ids=used_ids)
            if track:
                tracks.append(track)
                used_ids.add(track["id"])
        return tracks

    def play_tracks(self, track_uris: list[str]) -> None:
        """Start playback of the given tracks on the user's active device."""
        devices = self.sp.devices()
        active = next(
            (d for d in devices["devices"] if d.get("is_active")), None
        )
        if not active and devices["devices"]:
            active = devices["devices"][0]
        if not active:
            raise RuntimeError(
                "No active Spotify device found. Open Spotify on your phone or desktop first."
            )
        self.sp.start_playback(device_id=active["id"], uris=track_uris)
